version: '3.8'
services:
    webhook-base:
        build: webhook
        ports:
            - "9000:9000"
        volumes:
            - ./webhook/app:/app
            - ./.env:/.env
        env_file:
            - .env