version: '3.8'
services:
    server:
        build: node
        ports:
            - "9000:9000"
        volumes:
            - ./node/server:/app
        env_file:
            - .env
        entrypoint: run dev
        depends_on:
            adminer:
                condition: service_healthy
            db:
                condition: service_healthy

    safemode:
        build: node
        ports:
            - "9000:9000"
        volumes:
            - ./node/server:/node/server
        env_file:
            - .env
        entrypoint: tail -f /dev/null

    db:
        build: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5

    adminer:
        build: adminer
        ports:
            - 8080:8080
        healthcheck:
            test: curl -f http://localhost:8080
            interval: 1s
            retries: 100

volumes:
    postgres_volume: